#!/bin/bash

#       @(#)Copyright (c) 2023 Petre C. Crentz
#
#       This file is provided in the hope that it will
#       be of use.  There is absolutely NO WARRANTY.
#       Permission to copy, redistribute or otherwise
#       use this file is hereby granted provided that
#       the above copyright notice and this notice are
#       left intact.
#
#		Fluxuan Linux Snapshot Tool
#	
#		https://fluxuan.org - https://forums.fluxuan.org
#		Thank you for your interest in Fluxuan Linux !!

home=$(getent passwd $SUDO_USER | cut -d: -f6)
rsync_excludes=${rsync_excludes:="/tmp/exclude.list"}
conf=${disk_conf:="/tmp/disk.txt"}


d_conf() {
# writing to disk.txt
	local _conf=$1 _value=$2
	printf '%s\n' "${_conf}=${_value}" >> "$conf"
	
}

d_read() {
# reading from disk.txt
	local _conf=$1
	grep "${_conf}" "$conf" | cut -d '=' -f2
}


check_root (){
# check if running as root
[[ $(id -u) -eq 0 ]] || { echo -e "\t You need to be root!\n" ; exit 1 ; }
}

welcome_msg () {

whiptail --title "Fluxuan-Snapshot" --msgbox "Welcome to Fluxuan-Snapshot utility.
Fluxuan-Snapshot will create a bootable instalable ISO of your OS.
Fluxuan-Installer will be included to restore your OS in a short time.
Thank you for your interest in Fluxuan Linux. 

https://fluxuan.org   -   https://Forums.Fluxuan.org" 15 65

}

ask_part () {

hostname=$(whiptail --inputbox "Input your desired hostname" 8 78 fluxuan --title "Configuration..." 3>&1 1>&2 2>&3)
# The `3>&1 1>&2 2>&3` is a small trick to swap the stderr with stdout
# Meaning instead of return the error code, it returns the value entered

# Now to check if the user pressed OK or Cancel
exitstatus=$?
if [ $exitstatus = 0 ]; then
    d_conf HOSTNAME "$hostname"
else
    rm "$conf" ;
    exit 1 ;
fi


ISONAME=$(whiptail --inputbox "Input your desired ISONAME" 8 78 Fluxuan-Linux --title "Configuration..." 3>&1 1>&2 2>&3)
# The `3>&1 1>&2 2>&3` is a small trick to swap the stderr with stdout
# Meaning instead of return the error code, it returns the value entered

# Now to check if the user pressed OK or Cancel
exitstatus=$?
if [ $exitstatus = 0 ]; then
    d_conf ISONAME "$ISONAME"
else
    rm "$conf" ;
     exit 1 ;
fi



LABEL=$(whiptail --inputbox "Input your desired disk LABEL" 8 78 Fluxuan-Linux --title "Configuration..." 3>&1 1>&2 2>&3)
# The `3>&1 1>&2 2>&3` is a small trick to swap the stderr with stdout
# Meaning instead of return the error code, it returns the value entered

# Now to check if the user pressed OK or Cancel
exitstatus=$?
if [ $exitstatus = 0 ]; then
    d_conf LABEL "$LABEL"
else
    rm "$conf" ;
     exit 1 ;
fi


}

install_dep () {
 {
apt-get update && apt-get install rsync live-boot debootstrap squashfs-tools xorriso isolinux syslinux-efi grub-pc-bin grub-efi-amd64-bin grub-efi-ia32-bin mtools dosfstools resolvconf arch-install-scripts -y -qq &

for ((i=0; i<=100; i+=1)); do
        proc=$(ps aux | grep -v grep | grep -e "apt-get")
            if [[ "$proc" == "" ]]; then break; fi
            # Sleep for a longer period if the database is really big 
            # as dumping will take longer.
            sleep 1
            echo "$i"
           
        i=$(expr $i + 1)
        done
        # If it is done then display 100%
        echo 100
        # Give it some time to display the progress to the user.
        sleep 2
} | whiptail --gauge "Installing Dependencies..." 6 60 0
}

create_folders () {
{
mkdir -p $home/fluxuan_snapshot $home/fluxuan_snapshot/chroot
mkdir -p $home/fluxuan_snapshot/{staging/{EFI/BOOT,boot/grub/x86_64-efi,isolinux,live},tmp} 
for ((i=0; i<=100; i+=1)); do
        sleep 0.1
        echo "$i"
    done
} | whiptail --gauge "Creating Folders..." 6 60 0
}

check_excludes () {
 {
if ! [[ -f  $rsync_excludes ]] ; then
    rsync_excludes="/tmp/exclude.list"
    sleep 2
    cat > "$rsync_excludes" <<EOF
- /home/*/[a-zA-Z0-9]*
- /home/*/.cache
- /home/*/fluxuan_snapshot
- /dev/*
- /cdrom/*
- /media/*
- /target
- /swapfile
- /mnt/*
- /sys/*
- /proc/*
- /tmp/*
- /live
- /var/tmp/
- /var/cache/
- /etc/udev/rules.d/70-persistent-cd.rules
- /etc/udev/rules.d/70-persistent-net.rules
- /etc/mtab
- /home/*/.gvfs
- .gvfs
- .local/share/gvfs-metadata
- .cache
- .var/app/*/cache
- .var/app/*/.cache
- /.Trash
- .Trash-1*
- .local/share/Trash
- /Trash
- .xsession-errors
- .xsession-errors.old
- .wayland-errors
- .local/share/RecentDocuments
- .recently-used
- .recently-used.xbel
- recently-used.xbel
- .thumbnails
- .thumb
- Thumbs.db
- .DS_Store
- .localised
- .CFUserTextEncoding
- .zcompdump*
- .wget-hsts
- /boot/grub/grub.cfg
- /boot/grub/menu.lst
- /boot/grub/device.map
- /boot/*.bak
- /boot/*.old-dkms
- /etc/udev/rules.d/70-persistent-cd.rules
- /etc/udev/rules.d/70-persistent-net.rules
- /etc/fstab
- /etc/fstab.d/*
- /etc/mtab
- /etc/blkid.tab
- /etc/blkid.tab.old
- /etc/popularity-contest.conf
- /home/snapshot
- /lib/live/overlay
- /lib/live/image
- /lib/live/rootfs
- /lib/live/mount
- /run/*
- /var/log/[a-b,A-Z]*
- /var/log/[d-f]*
- /var/log/[h-z]*
- /var/log/*gz
- /var/cache/apt/archives/*.deb
- /var/cache/apt/pkgcache.bin
- /var/cache/apt/srcpkgcache.bin
- /var/cache/apt/apt-file/*
- /var/cache/debconf/*~old
- /var/lib/apt/lists/*
- /var/lib/apt/*~
- /var/lib/apt/cdroms.list
- /var/lib/aptitude/*.old
- /var/lib/dhcp/*
- /var/lib/dpkg/*~old
- /var/spool/mail/*
- /var/mail/*
- /var/backups/*.gz
- /var/backups/*.bak
- /var/lib/dbus/machine-id
- /var/lib/live/config/*
- /var/swap
- /var/swapfile
- /usr/share/icons/*/icon-theme.cache
- /root/.aptitude
- /root/.bash_history
- /root/.disk-manager.conf
- /root/.fstab.log
- /root/.lesshst
- /root/*/.log
- /root/.local/share/*
- /root/.nano_history
- /root/.synaptic
- /root/.VirtualBox
- /root/.ICEauthority
- /root/.Xauthority
- /root/.ssh
- /root/fluxuan_snapshot
- /home/*/.Trash*
- /home/*/.local/share/Trash/*
- /home/*/.mozilla/*/Cache/*
- /home/*/.mozilla/*/urlclassifier3.sqlite
- /home/*/.mozilla/*/places.sqlite
- /home/*/.mozilla/*/cookies.sqlite
- /home/*/.mozilla/*/signons.sqlite
- /home/*/.mozilla/*/formhistory.sqlite
- /home/*/.mozilla/*/downloads.sqlite
- /home/*/.adobe
- /home/*/.aptitude
- /home/*/.bash_history
- /home/*/.cache
- /home/*/.dbus
- /home/*/.gksu*
- /home/*/.gvfs
- /home/*/.lesshst
- /home/*/.log
- /home/*/.macromedia
- /home/*/.nano_history
- /home/*/.pulse*
- /home/*/.recently-used
- /home/*/.recently-used.xbel
- /home/*/.local/share/recently-used.xbel
- /home/*/.thumbnails/large/*
- /home/*/.thumbnails/normal/*
- /home/*/.thumbnails/fail/*
- /home/*/.vbox*
- /home/*/.VirtualBox
- /home/*/VirtualBox\ VMs
- /home/*/.xsession-errors*
- /home/*/.ICEauthority
- /home/*/.Xauthority
- /home/*/.gnupg
- /home/*/.ssh
- /home/*/.xchat2
- /home/*/.config/hexchat/logs/*
EOF
chmod 666 "$rsync_excludes"
fi 
for ((i=0; i<=100; i+=1)); do
        sleep 0.1
        echo "$i"
    done
} | whiptail --gauge "Creating Config Files..." 6 60 0
}

get_system () {
{
rsync -av --exclude-from="$rsync_excludes" / $home/fluxuan_snapshot/chroot &
for ((i=0; i<=100; i+=1)); do
        proc=$(ps aux | grep -v grep | grep -e "rsync")
            if [[ "$proc" == "" ]]; then break; fi
            # Sleep for a longer period if the database is really big 
            # as dumping will take longer.
            sleep 10
            echo "$i"
           
        i=$(expr $i + 1)
        done
        # If it is done then display 100%
        echo 100
        # Give it some time to display the progress to the user.
        sleep 2
        rm "$rsync_excludes"
} | whiptail --gauge "Preparing Filesystems...." 6 60 0
}
touch_boot () {
 {
touch $home/fluxuan_snapshot/staging/isolinux/isolinux.cfg
touch $home/fluxuan_snapshot/staging/boot/grub/grub.cfg
touch $home/fluxuan_snapshot/tmp/grub-embed.cfg
 for ((i=0; i<=100; i+=1)); do
        sleep 0.1
        echo "$i"
    done
} | whiptail --gauge "Preparing Boot Files...." 6 60 0
}
copy_boot () {
{
printf "" > $home/fluxuan_snapshot/chroot/etc/fstab
cp /etc/resolv.conf $home/fluxuan_snapshot/chroot/etc/resolv.conf
cp $home/fluxuan_snapshot/chroot/boot/vmlinuz-* $home/fluxuan_snapshot/staging/live/vmlinuz
cp $home/fluxuan_snapshot/chroot/boot/initrd.img-* $home/fluxuan_snapshot/staging/live/initrd
cp $home/fluxuan_snapshot/staging/boot/grub/grub.cfg $home/fluxuan_snapshot/staging/EFI/BOOT/
cp /usr/lib/ISOLINUX/isolinux.bin "$home/fluxuan_snapshot/staging/isolinux/"
cp /usr/lib/syslinux/modules/bios/* "$home/fluxuan_snapshot/staging/isolinux/"
cp -r /usr/lib/grub/x86_64-efi/* "$home/fluxuan_snapshot/staging/boot/grub/x86_64-efi/"
for ((i=0; i<=100; i+=1)); do
        sleep 0.1
        echo "$i"
    done
} | whiptail --gauge "Copying Boot Files...." 6 60 0
}

set_hostname() {
{
local hostname
	hostname=$(d_read HOSTNAME)

	echo "$hostname" > $home/fluxuan_snapshot/chroot/etc/hostname
	cat <<EOF > $home/fluxuan_snapshot/chroot/hosts
127.0.0.1	localhost
127.0.1.1	$hostname
# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
EOF
for ((i=0; i<=100; i+=1)); do
        sleep 0.1
        echo "$i"
    done
} | whiptail --gauge "Setting your hostname...." 6 60 0
}
print_menu () {
{
local ISONAME LABEL
	ISONAME=$(d_read ISONAME)
	LABEL=$(d_read LABEL)

printf "UI vesamenu.c32\n
\n
MENU TITLE $ISONAME Linux\n
DEFAULT linux\n
TIMEOUT 600\n
MENU RESOLUTION 640 480\n
MENU COLOR border       30;44   #40ffffff #a0000000 std\n
MENU COLOR title        1;36;44 #9033ccff #a0000000 std\n
MENU COLOR sel          7;37;40 #e0ffffff #20ffffff all\n
MENU COLOR unsel        37;44   #50ffffff #a0000000 std\n
MENU COLOR help         37;40   #c0ffffff #a0000000 std\n
MENU COLOR timeout_msg  37;40   #80ffffff #00000000 std\n
MENU COLOR timeout      1;37;40 #c0ffffff #00000000 std\n
MENU COLOR msg07        37;40   #90ffffff #a0000000 std\n
MENU COLOR tabmsg       31;40   #30ffffff #00000000 std\n
MENU BACKGROUND /boot/splash.png\n
\n
LABEL linux\n   
MENU LABEL $ISONAME [BIOS/ISOLINUX]\n
MENU DEFAULT\n  
KERNEL /live/vmlinuz\n   
APPEND initrd=/live/initrd boot=live\n\n   
$LABEL\n   
MENU LABEL $ISONAME [BIOS/ISOLINUX] (nomodeset)\n   
MENU DEFAULT\n   
KERNEL /live/vmlinuz\n   
APPEND initrd=/live/initrd boot=live nomodeset\n
EOF" > $home/fluxuan_snapshot/staging/isolinux/isolinux.cfg

printf "insmod part_gpt\n
insmod part_msdos\n
insmod fat\n
insmod iso9660\n
\n
insmod all_video\n
insmod font\n
background_image /boot/splash.png\n
\n
set default=\"0\"\nset timeout=30\n
\n
# If X has issues finding screens, experiment with/without nomodeset.\n
\nmenuentry \"$ISONAME [EFI/GRUB]\" {\n    
search --no-floppy --set=root --label $LABEL\n
linux (\$root)/live/vmlinuz boot=live\n    
initrd (\$root)/live/initrd\n}\n
\nmenuentry \"$ISONAME [EFI/GRUB] (nomodeset)\" {\n    
search --no-floppy --set=root --label $LABEL\n    
linux (\$root)/live/vmlinuz boot=live nomodeset\n    
initrd (\$root)/live/initrd\n}\n
EOF" > $home/fluxuan_snapshot/staging/boot/grub/grub.cfg

printf "if ! [ -d \"\$cmdpath\" ]; then\n    
# On some firmware, GRUB has a wrong cmdpath when booted from an optical disc.\n    
# https://gitlab.archlinux.org/archlinux/archiso/-/issues/183\n    
if regexp --set=1:isodevice '^(\([^)]+\))\/?[Ee][Ff][Ii]\/[Bb][Oo][Oo][Tt]\/?$' \"\$cmdpath\"; then\n        
cmdpath=\"\${isodevice}/EFI/BOOT\"\n    
fi\nfi\nconfigfile \"\${cmdpath}/grub.cfg\"\n
EOF" > $home/fluxuan_snapshot/tmp/grub-embed.cfg
for ((i=0; i<=100; i+=1)); do
        sleep 0.1
        echo "$i"
    done
} | whiptail --gauge "Creating Boot Menus...." 6 60 0
}

chroot_OS () {
if (whiptail --title "Chroot System" --yesno "Do you want to chroot into your system and install remove programs?" 8 78); then
mount --bind /proc $home/fluxuan_snapshot/chroot/proc
mount --bind /sys $home/fluxuan_snapshot/chroot/sys
mount --bind /dev $home/fluxuan_snapshot/chroot/dev
export HOME=/root
export LC_ALL=C
chroot $home/fluxuan_snapshot/chroot /bin/bash
else
continue
fi

}

make_change () {
whiptail --title "Make Changes" --msgbox "Your Operating System is ready for changes.
If you want to make any changes head to: 
-> /home/USER/fluxuan_snapshot/chroot <-
If you want a boot splash just add one to 
-> /home/USER/fluxuan_snapshot/staging/boot/splash.png <-

https://fluxuan.org   -   https://Forums.Fluxuan.org" 15 65 ;
umount $home/fluxuan_snapshot/chroot/proc
umount $home/fluxuan_snapshot/chroot/sys
umount $home/fluxuan_snapshot/chroot/dev
export HISTSIZE=0
}

squashing_filesystem () {
{
mksquashfs $home/fluxuan_snapshot/chroot $home/fluxuan_snapshot/staging/live/filesystem.squashfs -b 1048576 -comp xz -e boot &
for ((i=0; i<=100; i+=1)); do
        proc=$(ps aux | grep -v grep | grep -e "mksquashfs")
            if [[ "$proc" == "" ]]; then break; fi
            # Sleep for a longer period if the database is really big 
            # as dumping will take longer.
            sleep 20
            echo "$i"
           
        i=$(expr $i + 1)
        done
        # If it is done then display 100%
        echo 100
        # Give it some time to display the progress to the user.
        sleep 2
} | whiptail --gauge "Squashing Filesystems, it might take some time...." 6 60 0
}

write_grub () {
{
grub-mkstandalone -O i386-efi --modules="part_gpt part_msdos fat iso9660" --locales="" --themes="" --fonts="" --output="$home/fluxuan_snapshot/staging/EFI/BOOT/BOOTIA32.EFI" "boot/grub/grub.cfg=$home/fluxuan_snapshot/tmp/grub-embed.cfg" &&
grub-mkstandalone -O x86_64-efi --modules="part_gpt part_msdos fat iso9660" --locales="" --themes="" --fonts="" --output="$home/fluxuan_snapshot/staging/EFI/BOOT/BOOTx64.EFI" "boot/grub/grub.cfg=$home/fluxuan_snapshot/tmp/grub-embed.cfg"
for ((i=0; i<=100; i+=1)); do
        sleep 0.1
        echo "$i"
    done
} | whiptail --gauge "Creating EFI files...." 6 60 0
}

build_iso () {
{
cd $home/fluxuan_snapshot/staging &&
dd if=/dev/zero of=efiboot.img bs=1M count=20 &&
mkfs.vfat efiboot.img &&
mmd -i efiboot.img ::/EFI ::/EFI/BOOT &&
mcopy -vi efiboot.img $home/fluxuan_snapshot/staging/EFI/BOOT/BOOTIA32.EFI $home/fluxuan_snapshot/staging/EFI/BOOT/BOOTx64.EFI $home/fluxuan_snapshot/staging/boot/grub/grub.cfg ::/EFI/BOOT/ &&
xorriso -as mkisofs -iso-level 3 -o "$home/fluxuan_snapshot/$ISONAME.iso" -full-iso9660-filenames -volid "$LABEL" --mbr-force-bootable -partition_offset 16 -joliet -joliet-long -rational-rock -isohybrid-mbr /usr/lib/ISOLINUX/isohdpfx.bin -eltorito-boot isolinux/isolinux.bin -no-emul-boot -boot-load-size 4 -boot-info-table --eltorito-catalog isolinux/isolinux.cat -eltorito-alt-boot -e --interval:appended_partition_2:all:: -no-emul-boot -isohybrid-gpt-basdat -append_partition 2 C12A7328-F81F-11D2-BA4B-00A0C93EC93B $home/fluxuan_snapshot/staging/efiboot.img "$home/fluxuan_snapshot/staging" &&
chmod 755 $home/fluxuan_snapshot/"$ISONAME".iso
for ((i=0; i<=100; i+=1)); do
        sleep 0.1
        echo "$i"
    done
} | whiptail --gauge "Creating your .ISO...." 6 60 0
}

finish () {
rm "$conf"
rm "rsync_excludes"
whiptail --title "Fluxuan-Snapshot" --msgbox "Thank you for using Fluxuan-Snapshot.
Thank you for your interest in Fluxuan Linux.

For any help please join out Forums.

Your Bootable ISO file is in:
-> /home/USER/fluxuan_snapshot/

https://fluxuan.org   -   https://Forums.Fluxuan.org" 15 65
}

do_install () {
	welcome_msg
	ask_part
	install_dep
	create_folders
	check_excludes
	get_system
	touch_boot
	copy_boot
	set_hostname
	print_menu
	chroot_OS
	make_change
	squashing_filesystem
	write_grub
	build_iso
	finish
	}
	
do_install
